### ISSUE TITLE
Novas features e correção de bugs

### ISSUE THREAD

**Issue by FihFafnir** [Pedro-H-Gregorio/organizador-receitas#10]
Adicionar listagem de receitas antes da busca, e correção de possíveis bugs.

**Comment by Pedro-H-Gregorio** [comment]
https://github.com/Pedro-H-Gregorio/organizador-receitas/assets/89112072/eb5d3bbc-be74-4d23-a416-c7a7e056acf2

**Comment by Pedro-H-Gregorio** [comment]
E falta fazer a listagem de todos os titulos de receitas
